import java.util.*;
/*
Create a java program. Your program should have an array of booleans of length 10 that will represent people’s opinion about a new they read on facebook.
The data that will be inserted on the array will be generated by using the random.nextBoolean() method inside a for loop.
After generating the values, print how many people believe that the new is real and print how many people thinks the new is a hoax.
*/
public class Exercise12{
    public static void main(String[] args){
        Random rd = new Random();
        boolean[] blnArr = new boolean[10];
        //boolean blnArr[] = new boolean[10];
        int sumT = 0;
        int sumF = 0;
        for (int i = 0; i < blnArr.length; i++){
            blnArr[i] = rd.nextBoolean();
            //System.out.println(blnArr[i]);
            if (blnArr[i] == true){
                sumT +=1;
            }
        }        
        sumF = blnArr.length - sumT;
        System.out.println("\nThere are "+sumT+" people think the new is real in Facebook!");
        System.out.println("There are "+sumF+" people think the new is a hoax in Facebook!");
    }
}